version: 2

sources:
  - name: sap
    description: fonte do ERP da Adventure Works
    database: equatorial
    schema: DBT_FMACHADO_AW_SAP

    tables:
      - name: product
        columns:
          - name: productid
            tests:
              - unique
              - not_null
          - name: name
            tests:
              - unique
              - not_null              
                
      - name: productcategory
        columns:
          - name: productcategoryid
            tests:
              - unique
              - not_null
      - name: productsubcategory
        columns:
          - name: subproductcategoryid
            tests:
              - unique
              - not_null

      - name: person
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null         

      - name: customer
        columns:
          - name: customerid
            tests:
              - unique
              - not_null    

      - name: personcreditcard
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null     
          - name: creditcardid
            tests:
              - unique
              - not_null             


      - name: creditcard
        columns:
          - name: creditcardid
            tests:
              - unique
              - not_null 

      - name: store
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null     
          - name: salespersonid
            tests:
              - unique
              - not_null      

      - name: emailaddress
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null     
          - name: emailaddressid
            tests:
              - unique
              - not_null                  

      - name: personphone
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null  

      - name: phonenumbertype
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null       
        
      - name: businessentity
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null        
            
             
              