version: 2

sources:
  - name: sap
    description: fonte do ERP da Adventure Works
    database: equatorial
    schema: dbt_fmachado_aw_sap

    tables:
      - name: product
        columns:
          - name: productid
            tests:
              - unique
              - not_null
          - name: name
            tests:
              - unique
              - not_null              
                
      - name: productcategory
        columns:
          - name: productcategoryid
            tests:
              - unique
              - not_null
      - name: productsubcategory
        columns:
          - name: subproductcategoryid
            tests:
              - unique
              - not_null
        





